### PR TITLE
Refactor code to remove code-duplication

### PR DESCRIPTION
**Pull request by richyen**
This consolidates visualizer targets into the visualizer package.  This will eventually make way for the possibility of passing in `--target=custom`, along with `--post_url` and `--plan_key`, so users can post their plans to local installs of say, depesz (see https://gitlab.com/depesz/explain.depesz.com/-/blob/master/Vagrantfile for an example of how someone might deploy their own explain.depesz.com instance)

Linted -- one lint error re. "unreachable code" at the end of `visualizer.go` (what if `target` matches nothing?)

### CODE REVIEW

**Comment by agneum** [comment]
@richyen Thanks for you PR.

I think we should keep separate structs, as this allows us to provide an appropriate level of abstraction.

I noticed these visualization platforms are slightly different. Submission forms contain various fields. For example, there are titles, queries, flags for visibility, and obfuscation which would be useful. 
Combining all these packages into one may be inconvenient from the point of view of the further development of the exporter tool.

**Comment by richyen** [comment]
> I think we should keep separate structs, as this allows us to provide an appropriate level of abstraction.

Yeah, that makes sense.  But perhaps we can fold in the constants into the struct itself?

And what if we implement some inheritance so that the `Export` method belongs to the `visualizer` class, rather than each of the separate service classes?  Or would you prefer to keep those abstracted as well?

**Comment by agneum** [comment]
I would prefer to store packages separately.
Thus, we can easily change the logic without affecting other structures. This allows us to keep the code simple and decoupled. We do not force the exporter to work through POST requests, and at the same time, we are flexible in changing the sent fields for each target service.

**Comment by richyen** [comment]
Gonna withdraw this PR as it seems clear that the roadmap will include separate packages for each visualizer

**Pull request closed without merging**
